### PR TITLE
Refreshed the overview image

### PR DESCRIPTION
**Pull request by bobmulder**

### CODE REVIEW

**Comment by Odonno** [comment]
Yep, I need to refresh it.
Don't you have an image with notification number ?

**Comment by bobmulder** [comment]
If you send me one at the gitter of this repo I will do it again ;)

**Comment by bobmulder** [comment]
What about this @Odonno?

**Comment by Odonno** [comment]
Perfect

**Comment by bobmulder** [comment]
Cool! Btw: I See the chat order is changing now but can't figure out how you decide the order??

**Comment by bobmulder** [comment]
Don't forget to pull it to the store as well ;)

**Pull request merged**
