### PR TITLE
chore(app): Remove project.lock.json file and add exclusion to .gitig…

### PR DESCRIPTION
**Pull request by gep13**
…nore file

### CODE REVIEW

**Comment by Odonno** [comment]
Yep ! Did not see that.

Just a thing : MAJ on commit message, so should be

    chore(app): remove project.lock.json file and add exclusion to .gitignore file

**Comment by gep13** [comment]
@Odonno done.

Out of interest, what is MAJ?

**Comment by Odonno** [comment]
Sorry, it's french for uppercase. :)

**Comment by gep13** [comment]
Ha ha, no worries :+1: I thought it might be that, but just wanted to make sure.

**Pull request merged**
