### PR TITLE
fix(review): use WP8.x schema for store link

### PR DESCRIPTION
**Pull request by gep13**
- As per the information in this StackOverflow Post:
http://stackoverflow.com/a/22979016/671491

I have been reliably informed that we can't actually test this until the application is deployed from the store.  When I test this locally, is opens an empty Review Page:

image

Which I suspect would be populated with your actual package coming from the store.

### CODE REVIEW

**Comment by gep13** [comment]
@Odonno I have just force pushed some changes.  Can you let me know what you think?  I am just signing out for the night, but will check in tomorrow.

**Comment by Odonno** [comment]
Force pushed ? What do you mean ?

**Comment by gep13** [comment]
I added a new commit locally to my branch, and then I did:

```
git rebase -i master
```

I then used `fixup` to essentially squash the two commits together, re-writing the history of the branch.  Then, in order to push the changes onto my branch, through to this PR, I had to use:

```
git push -f
```

Which is a forced push.

**Comment by gep13** [comment]
So, looking again at this, I still think we need ```#if WINDOWS_PHONE_APP``` in order to make use of `CurrentApp`.

Are you happy to proceed on that basis, leaving the `#else` to cover the UWP versions?

**Comment by Odonno** [comment]
I'll try. No worries.

**Comment by Odonno** [comment]
To choose, I'll prefer the merged and easiest way. If we can do without `#if`, we'll do. If it does not work in production, we'll adapt the code !

    await Windows.System.Launcher.LaunchUriAsync(new Uri("ms-windows-store:reviewapp"));

**Comment by gep13** [comment]
fixed up as suggested.

**Comment by Odonno** [comment]
Fixed #31

**Pull request merged**
