### PR TITLE
feat(app): add german translation

### PR DESCRIPTION
**Pull request by NPadrutt**
Besides the translation for german I added a entry to all culturues for the plural char. Before it was "s"
for english and french, but in german you need a "n".

### CODE REVIEW

**Comment by gep13** [comment]
This is a great addition to the application! Danke! :+1:

**Comment by Odonno** [comment]
@NPadrutt Nice !

Can you follow the commit convention ?

**Comment by NPadrutt** [comment]
yeah, I guess an entry in the readme would be helpful. Then everyone knows what your commit convention is ^^

**Comment by Odonno** [comment]
@NPadrutt Ok, I'll do that #47

**Comment by NPadrutt** [comment]
Keep me posted

**Comment by NPadrutt** [comment]
maybe a stupid question.. I changed the title of the pr. But as far as I know there isn't a way to change the commit message. Or is there?

**Comment by gep13** [comment]
>@NPadrutt said...
maybe a stupid question.. I changed the title of the pr. But as far as I know there isn't a way to change the commit message. Or is there?

Not through the GitHub UI, no, but you can do this through either a `git commit --amend` or through a `git rebase`.  Once you have done that, you will have to do a `git push -f`.  Are you familiar with using this approach?

**Comment by gep13** [comment]
@NPadrutt you can find some guidance on doing this here:

https://github.com/chocolatey/choco/blob/master/CONTRIBUTING.md#respond-to-feedback-on-pull-request

Let me know if you run into any problems.

**Comment by Odonno** [comment]
Like @gep13 said. You can use `git commit --amend` on your last commit.
If you need to rewrite more than 1 commit, you can use `git rebase -i`.

I don't great UI about that, I am used to command line. :)

**Comment by gep13** [comment]
>@Odonno said...
I don't great UI about that, I am used to command line. :)

I have never found a good UI for rebasing.  Personally, I think this is always something that you need to drop to the command line for.

**Comment by Odonno** [comment]
@gep13 I think there could a great software (with good UI) for `git rebase -i`. But it need to be dedicated to do that.

**Comment by NPadrutt** [comment]
I updated the commit and the PR. Can you have a look again?

**Comment by Odonno** [comment]
Looks fine !

@gep13 What do you think ?

**Comment by gep13** [comment]
LGTM :-)

**Pull request merged**
